
/*
	Copyright (C) 2013-2026 CrownSoft
  
	This software is provided 'as-is', without any express or implied
	warranty.  In no event will the authors be held liable for any damages
	arising from the use of this software.

	Permission is granted to anyone to use this software for any purpose,
	including commercial applications, and to alter it and redistribute it
	freely, subject to the following restrictions:

	1. The origin of this software must not be misrepresented; you must not
	   claim that you wrote the original software. If you use this software
	   in a product, an acknowledgment in the product documentation would be
	   appreciated but is not required.
	2. Altered source versions must be plainly marked as such, and must not be
	   misrepresented as being the original software.
	3. This notice may not be removed or altered from any source distribution.	  
*/

#pragma once

#include "../core/CoreModule.h"
#include "KFont.h"
#include "KCursor.h"

/**
	Base class of all W32 gui objects.
	GUI in RFC uses logical units instead of pixels. on 96 dpi, logical unit is equal to a pixel.
	In otherwords, logical value is a value which is used for 96 dpi.
	so x,y,width,height are always in logical units. we calculate real pixel value using the current dpi.
	therefore setting position or size does not have to care about whether window is created or not.
	use of logical values allow user to use the same values before or after creating the window.
*/
class KComponent
{
protected:
	KString compClassName;
	KString compText;
	HWND compHWND;
	HWND compParentHWND;
	DWORD compDwStyle;
	DWORD compDwExStyle;
	UINT compCtlID;
	Logical compLX;
	Logical compLY;
	Logical compLWidth;
	Logical compLHeight;
	bool compVisible;
	bool compEnabled;
	bool isRegistered;
	bool shouldRegisterClassName;
	KFontReference compFontRef;
	void* userParam;

	virtual void afterCreated() noexcept;
public:
	WNDCLASSEXW wc;

	/**
		Constructs a standard win32 component.
		@param generateWindowClassDetails	set to false if you are not registering window class and using standard class name like BUTTON, STATIC etc... wc member is invalid if generateWindowClassDetails is false.
	*/
	KComponent(bool generateWindowClassDetails) noexcept;
	
	/**
		Returns HWND of this component
	*/
	operator HWND()const noexcept;

	/**
		Called after hotplugged into a given HWND.
	*/
	virtual void onHotPlug() noexcept;

	/**
		HotPlugs given HWND. this method does not update current compFont and cursor variables.
		Set fetchInfo to true if you want to acquire all the information about this HWND. (width, height, position etc...)
		Set fetchInfo to false if you just need to receive events. (button click etc...)
	*/
	virtual void hotPlugInto(HWND component, bool fetchInfo = true) noexcept;

	/**
		@returns autogenerated unique class name for this component
	*/
	KString getComponentClassName() noexcept;

	/**
		Registers the class name and creates the component. 
		Set requireInitialMessages to true to receive initial messages (WM_CREATE etc.)
		@returns false if registration failed or component creation failed.
		setDPI must be called after calling create method to correctly size for dpi.
	*/
	virtual bool create(bool requireInitialMessages = false) noexcept;

	// called when parent receive WM_DESTROY message.
	virtual void onParentDestroy() noexcept;

	virtual void destroy() noexcept;

	/**
		Handles internal window messages. (subclassed window proc)
		Important: Pass unprocessed messages to parent if you override this method.
	*/
	virtual LRESULT windowProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam) noexcept;

	/**
		Receives messages like WM_COMMAND, WM_NOTIFY, WM_DRAWITEM from the parent window. (if it belongs to this component)
		Pass unprocessed messages to parent if you override this method.
		@returns true if msg processed.
	*/
	virtual bool eventProc(UINT msg, WPARAM wParam, LPARAM lParam, LRESULT* result) noexcept;

	/**
		Identifier of the child component which can be used with WM_MEASUREITEM like messages.
		@returns zero for top level windows
	*/
	UINT getControlID() noexcept;

	/**
		Sets font type of this component.
	*/
	virtual void setFontType(const KFontType& fontType) noexcept;

	/**
		Returns the font type of this component
	*/
	KFontType getFontType() noexcept;

	/**
		Returns caption of this component
	*/
	virtual KString getText() noexcept;

	/**
		Sets caption of this component
	*/
	virtual void setText(const KString& compText) noexcept;

	void setHWND(HWND compHWND) noexcept;

	/**
		Returns HWND of this component
	*/
	HWND getHWND() noexcept;

	/**
		Changes parent of this component
	*/
	void setParentHWND(HWND compParentHWND) noexcept;

	/**
		Returns parent of this component
	*/
	HWND getParentHWND() noexcept;

	/**
		Returns style of this component
	*/
	DWORD getStyle() noexcept;

	/**
		Sets style of this component
	*/
	void setStyle(DWORD compStyle) noexcept;

	/**
		Returns exstyle of this component
	*/
	DWORD getExStyle() noexcept;

	/**
		Sets exstyle of this component
	*/
	virtual void setExStyle(DWORD compExStyle) noexcept;

	/**
		Returns logical x position of this component which is relative to parent component.
	*/
	virtual Logical getX() noexcept;

	/**
		Returns logical y position of this component which is relative to parent component.
	*/
	virtual Logical getY() noexcept;

	/**
		Returns logical width of the component.
	*/
	Logical getWidth() noexcept;

	/**
		Returns logical height of the component.
	*/
	Logical getHeight() noexcept;

	/**
		Returns logical right edge (x + width) of the component.
	*/
	Logical getRight() noexcept;

	/**
		Returns logical bottom edge (y + height) of the component.
	*/
	Logical getBottom() noexcept;

	// dpi is 96 if the component is not created.
	inline int getDPI() noexcept
	{
		return (compHWND != NULL) ? KDPIUtility::getWindowDPI(compHWND) : USER_DEFAULT_SCREEN_DPI;
	}

	/**
		Sets logical width and height of the component.
	*/
	virtual void setSize(Logical width, Logical height) noexcept;

	/**
		Sets physical width and height of the component. component must be created first.
	*/
	virtual void setSizePhysical(Physical width, Physical height) noexcept;

	/**
		Sets logical x and y position of the component. x and y are relative to parent component
	*/
	virtual void setPosition(Logical x, Logical y) noexcept;

	/**
		Sets logical x, y, width and height of the component in a single call.
		x and y are relative to parent component.
	*/
	virtual void setBounds(Logical x, Logical y, Logical width, Logical height) noexcept;

	// --- Positioning relative to another component. spacing is a logical value. ---
	// The width and height of both this component and the target must be set before calling these methods.
	void placeToRightOf(KComponent& target, Logical spacing = 10) noexcept;
	void placeToLeftOf(KComponent& target, Logical spacing = 10) noexcept;
	void placeBelow(KComponent& target, Logical spacing = 10) noexcept;
	void placeAbove(KComponent& target, Logical spacing = 10) noexcept;

	// --- Alignments with another component ---
	// The width and height of both this component and the target must be set before calling these methods.
	void alignTopWith(KComponent& target) noexcept;
	void alignBottomWith(KComponent& target) noexcept;
	void alignLeftWith(KComponent& target) noexcept;
	void alignRightWith(KComponent& target) noexcept;
	void alignCenterHorizontallyWith(KComponent& target) noexcept;
	void alignCenterVerticallyWith(KComponent& target) noexcept;

	virtual void setDPI(int newDPI) noexcept;

	/**
		Sets visible state of the component
	*/
	virtual void setVisible(bool state) noexcept;

	/**
		Returns visible state of the component
	*/
	bool isVisible() noexcept;

	/**
		Returns the component is ready for user input or not
	*/
	bool isEnabled() noexcept;

	/**
		Sets component's user input reading state
	*/
	virtual void setEnabled(bool state) noexcept;

	/**
		Brings component to front
	*/
	void bringToFront() noexcept;

	/**
		Grabs keyboard focus into this component
	*/
	void setKeyboardFocus() noexcept;

	/**
		Repaints the component
	*/
	virtual void repaint() noexcept;

	/**
		Attaches an application-defined value to this component. Not used by the framework itself.
	*/
	void setParam(void* userParam) noexcept;

	/**
		Returns the value previously set by setParam. Returns nullptr if never set.
	*/
	void* getParam() noexcept;

	virtual ~KComponent() noexcept;

private:
	RFC_LEAK_DETECTOR(KComponent)
};


// macros to handle window messages

#define BEGIN_KMSG_HANDLER \
	virtual LRESULT windowProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam) noexcept override \
	{\
	switch(msg)\
	{

#define ON_KMSG(_KMsg,_KMsgHandler) \
	case _KMsg: return _KMsgHandler(wParam,lParam);

// msvc & clang supports __super keyword

#define END_KMSG_HANDLER \
	default: return __super::windowProc(hwnd,msg,wParam,lParam); \
	}\
	}

